### PR TITLE
Remove linter excluding rules, clean up code

### LINKED ISSUE #22: Include more errors into lint check
I see that we have - `Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked in the linter config`.

Although I understand that some of the errors are unlikely to ever happen, I suggest that we remove this or at least include some of its parts and modify the code to be more robust in case of such unexpected scenarios. Such an approach leads to heavy error ignoring all around the code (my concern arised when I took a look at `therealssh` code)

_Originally posted by @Darkren in https://github.com/skycoin/skywire/issues/460_

### PR DESCRIPTION
**Pull request by nkryuchkov**
Fixes #22 

 Changes:	
- Removed all linter excluding rules
- Removed all `nolint` comments except a couple of them that are really necessary
- Fixed all linter issues after removal
- Made some code cleanup

### CODE REVIEW

File: client_test.go [hunk 1]
```diff
@@ -143,12 +143,14 @@ func TestClient(t *testing.T) {
 
 		ctx := context.TODO()
 
+		serveErrCh1 := make(chan error, 1)
```
Comment (evanlinjin) [inline client_test.go:146]: I prefer the following pattern:
```golang
done1 := make(chan struct{})
var err1 error
go func () {
    err1 = conn1.Server(ctx, ch1)
    close(done1)
}()
<-done1

```
As it ensures the good habit of closing channels after they are created.

**Review by evanlinjin — APPROVED** [review]

**Review by ivcosla — APPROVED** [review]
good job

File: client_test.go (hunk 1 above)
Comment (nkryuchkov) [reply client_test.go:146]: @evanlinjin What if we close the `serveErrCh1` channel after sending to it an error returned by `Serve`? I think this way we can reduce the amount of code

Comment (evanlinjin) [reply client_test.go:146]: > @evanlinjin What if we close the `serveErrCh1` channel after sending to it an error returned by `Serve`? I think this way we can reduce the amount of code

I guess that can work too.

Comment (nkryuchkov) [reply client_test.go:146]: @evanlinjin Fixed

File: noise/net_test.go [hunk 2]
```diff
@@ -91,7 +91,7 @@ func TestRPCClientDialer(t *testing.T) {
 			require.NoError(t, conn.Close())
 		}
 
-		_ = d.Close()
+		require.NoError(t, d.Close())
```
Comment (evanlinjin) [inline noise/net_test.go]: I think it is better if we don't check this error. Line 91 also closes the same connection, and hence, this may return an error.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Good stuff. One more small thing.

File: noise/net_test.go (hunk 2 above)
Comment (nkryuchkov) [reply noise/net_test.go]: @evanlinjin Thanks for pointing out. Fixed.

**Review by evanlinjin — APPROVED** [review]
